#app
server:
  port: 8080

spring:
  application:
    name: mybatis-plus-example
  profiles:
    active: dev

#mybatis
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fengwenyi.mybatisplusexample.entity
  # 扫描枚举类 # 支持统配符 * 或者 ; 分割
  type-enums-package: com.fengwenyi.mybatisplusexample.entity.enums
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      # logic-delete-field: delete_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑删除
      logic-not-delete-value: 0 # 正常
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

logback:
  appName: mybatis-plus-example
  fileType: log
