#spring
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.16.128:3306/mybatis-plus-example
    username: root
#    password: kU#m5eHY5iTiQj#q
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.16.128:3306/mybatis-plus-example

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev

logging:
  level:
    com.fengwenyi.mybatis_plus_example.service.impl: trace
    com.fengwenyi.mybatis_plus_example.controller: trace
