#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-plus-example
    username: root
#    password: kU#m5eHY5iTiQj#q
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev

logging:
  level:
    com.fengwenyi.mybatis_plus_example.service.impl: trace
    com.fengwenyi.mybatis_plus_example.controller: trace
